[package]
name = "py-promql-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "promql_parser"
crate-type = ["cdylib"]

[dependencies]
promql-parser = { git = "https://github.com/GreptimeTeam/promql-parser.git", branch = "develop" }
pyo3 = { version = "0.17.3", features = ["abi3-py37", "extension-module"] }
